import React, { FC } from "react";

const Article = [
  {
    title: "1. Vancouver",
    image: require("./assets/vancouver.png"),
    article:
      "Vancouver is a major city in western Canada, located in the Lower Mainland region of British Columbia. As the most populous city in the province, the 2021 census recorded 662,248 people in the city, up from 631,486 in 2016. The Greater Vancouver area had a population of 2.6 million in 2021, making it the third-largest metropolitan area in Canada. Vancouver has the highest population density in Canada, with over 5,700 people per square kilometre. Vancouver is one of the most ethnically and linguistically diverse cities in  Canada: 46 percent of its residents are not native English speakers, 44 percent are native speakers of neither English nor French, and 51.6 percent of residents belong to visible minority groups. Vancouver is one of the most livable cities in Canada and in the world. In terms of housing affordability, Vancouver is also one of the most expensive cities in Canada and in the  world. Vancouver plans to become the greenest city in the world. Vancouverism is the city's urban planning design philosophy. Vancouver has hosted many international conferences and events, including the 1954 Commonwealth Games, UN Habitat I, Expo 86, APEC Canada 1997, the World Police and Fire Games in 1989 and 2009; several matches of 2015 FIFA Women's World Cup including the finals at BC Place in Downtown Vancouver, and the 2010 Winter Olympics and Paralympics which were held in Vancouver and Whistler, a resort community 125 km (78 mi) north of the city. In 1969, Greenpeace was founded in Vancouver. The city became the permanent home to TED conferences in 2014.",
  },
  {
    title: "2. Niagara Falls",
    image: require("./assets/niagara.png"),
    article:
      "Canada's most famous natural attraction, the majestic Niagara Falls has been drawing sightseers almost since its discovery. The great wall of water pounding over the falls is an amazing sight, and the view and access afforded visitors is astounding. You can literally walk up to the edge of the falls, separated only by a cast iron railing, and see the water as it disappears over the crest. In 2021, the Niagara Parks Commission opened the 115-year-old Canadian Niagara Power Company generating station. After years of painstaking renovations and rehabilitation,  this fascinating building displays its old generators and electrical equipment. The plan is to allow visitors to descend beneath the building and walk through former water tunnels, ending up at the river's edge below the falls. The city that has developed here, also named Niagara Falls, has been greatly influenced by the people and atmosphere the falls have created. Stuntmen and daredevils have been  tempting their fate on the falls throughout the decades, and as a result, a carnival-style atmosphere has come to define this unique city. Just a short drive from Toronto, Niagara Falls is easy to reach, and the city is a fun place to spend a day or two.",
  },
  {
    title: "3. Toronto",
    image: require("./assets/tront.png"),
    article:
      "Toronto is the capital city of the Canadian province of Ontario. With a recorded population of 2,794,356 in 2021, it is the most populous city in Canada and the fourth most populous city in North America. The city is the anchor of the Golden Horseshoe, an urban agglomeration of 9,765,188 people (as of 2021) surrounding the western end of Lake Ontario, while the Greater Toronto Area proper had a 2021 population of 6,712,341. Toronto is an international centre of business, finance, arts, sports and culture, and is recognized as one of the most multicultural and cosmopolitan cities in the world.Indigenous peoples have travelled through and inhabited the Toronto area, located on a broad sloping plateau interspersed with rivers, deep ravines, and urban forest, for more than 10,000 years. After the broadly disputed Toronto Purchase, when the Mississauga surrendered the area to the British Crown, the British established the town of York in 1793 and later designated it as the capital of Upper Canada. During the War of 1812, the town was the site of the Battle of York and suffered heavy damage by American troops. York was renamed and incorporated in 1834 as the city of Toronto. It was designated as the capital of the province of Ontario in 1867 during Canadian Confederation.The city proper has since expanded past its original limits through both annexation and amalgamation to its current area of 630.2 km2 (243.3 sq mi). The diverse population of Toronto reflects its current and historical role as an important destination for immigrants to Canada. More than 50 percent of residents belong to a visible minority population group, and over 200 distinct ethnic origins are represented among its inhabitants. While the majority of Torontonians speak English as their primary language, over 160 languages are spoken in the city. The mayor of Toronto is elected by direct popular vote to serve as the chief executive of the city. The Toronto City Council is a unicameral legislative body, comprising 25 councillors since the 2018 municipal election, representing geographical wards throughout the city.",
  },
  {
    title: "4. Montreal",
    image: require("./assets/montreal.png"),
    article:
      "Montreal is a unique city, with a beautiful old historic district dating back to the 1600s and a modern city center with extensive underground shopping. Old Montreal is the main tourist hub, with cobbled streets and fantastic old buildings, a perfect place to lose yourself as you wander up and down the historical streets. In and around Montreal are a fine assortment of wonderful parks and beaches. Montreal is also home to a large number of fashion designers, and high-end boutiques line the historic streets, along with quaint hotels and restaurants. Located in the French-speaking province of Québec, Montreal has its own cultural identity, but English-speaking visitors will have no trouble communicating with anyone in the tourist industry.",
  },
  {
    title: "5. Banff National Park",
    image: require("./assets/banff.png"),
    article:
      "The charming mountain town of Banff, in the stunning Banff National Park, is a must-visit destination for anyone looking to explore the Rocky Mountains and see some of the most beautiful scenery in Canada. This is undeniably a tourist town, catering to international travelers from all over the globe.In summer, the turquoise lakes, including Lake Louise and Moraine Lake, set below glacier-capped mountains are a glorious sight. One of the best ways to experience the landscape is to drive the Icefields Parkway, which runs through the park to Jasper National Park. For those looking for a bit more adventure and exercise, consider tackling one of Banff's best hiking trails. These classic routes take you to some of the most impressive sights in the park. In winter, skiers and boarders descend on the area to enjoy the slopes of Lake Louise Ski Resort and Sunshine Village Ski Resort, two of Canada's best ski resorts. But you don't even need to leave the town of Banff to enjoy a gondola ride to the top of a mountain for dinner, soak in a hot springs-fed pool, find fabulous shopping, discover lovely walking trails, and possibly see elk and woodland caribou that frequently make their way into town.",
  },
];

export default Article;
